-- SCHOOL
INSERT INTO SCHOOL VALUES ('oom', '大原学園');

-- CLASS_NUM
INSERT INTO CLASS_NUM VALUES ('oom', '131');

-- SUBJECT
INSERT INTO SUBJECT VALUES ('oom', 'A01', '国語');
INSERT INTO SUBJECT VALUES ('oom', 'A02', '数学');

-- STUDENT
INSERT INTO STUDENT VALUES ('2231111', '山田太郎', 2023, '131', TRUE, 'oom');
INSERT INTO STUDENT VALUES ('2231112', '佐藤花子', 2023, '131', TRUE, 'oom');

-- TEST（空でOK）
